Models/Seller.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Market.Models
{
    public class Seller
    {
        [Key]
        public int SellerId  { get; set; }

        [Required]
        public string Name { get; set; }
        [Required]
        public string MobileNumber { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        [Range(0, 5)]
        public int Rating { get; set; }
    }
}

Controllers/SellerController.cs
using Market.Models;
using Market.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Market.Controllers
{
    public class SellerController : Controller
    {
        // GET: Student
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetAllSellers()
        {

            SellerRepository ProRepo = new SellerRepository();
            ModelState.Clear();
            return View(ProRepo.GetAllSellers());
        }  

        public ActionResult AddSeller()
        {
            return View();
        }

        // POST: Product/AddProduct   
        [HttpPost]
        public ActionResult AddSeller(Seller Emp)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    SellerRepository ProRepo = new SellerRepository();

                    if (ProRepo.AddSeller(Emp))
                    {
                        ViewBag.Message = "Seller added successfully";
                    }
                }

                return View();
            }
            catch
            {
                return View();
            }
        }

        //[HttpGet]
        //public ActionResult ViewSell(int? id)
        //{
        //    SellerRepository ProRepo = new SellerRepository();
        //    ModelState.Clear();
        //    return View(ProRepo.GetData(id));
        //}

        public ActionResult Details(int id)
        {
            SellerProductRepository ProRepo = new SellerProductRepository();
            ModelState.Clear();
            Session["SellerId"] = id;
            return View(ProRepo.SellersProduct(id));
        }


        public ActionResult AddSellersproduct()
        {
            SellerRepository sr = new SellerRepository();
            ProductRepository pr = new ProductRepository();
            ViewBag.SList = sr.GetAllSellers().Select(i => new { i.SellerId, i.Name });
            var PList = pr.GetAllProducts();
            List<SelectListItem> FProduct = new List<SelectListItem>();

            foreach (var item in PList)
            {
                FProduct.Add
                    (new SelectListItem
                    {
                    Text=item.Name,
                    Value=item.ProductId.ToString()
                    });
            }
            ViewBag.ProList = FProduct;
            return View();
        }

        // POST: Product/AddProduct   
        [HttpPost]
        public ActionResult AddSellersproduct(SellerProduct Emp)
        {
            try
            {
                Emp.SellerId = Convert.ToInt32(Session["SellerId"]);
                if (ModelState.IsValid)
                {
                    SellerProductRepository ProRepo = new SellerProductRepository();

                    if (ProRepo.AddSellersproduct(Emp))
                    {
                        ViewBag.Message = "Sellers Product added successfully";
                    }
                }

                return RedirectToAction("Details", new { id = Emp.SellerId });
            }
            catch
            {
                return View();
            }
        }


        //public ActionResult DeleteSellerProduct(int id, int SellerId)
        //{
        //    try
        //    {
        //        SellerProductRepository ProRepo = new SellerProductRepository();
        //        if (ProRepo.DeleteSellerProduct(id))
        //        {
        //            ViewBag.AlertMsg = "Seller details deleted successfully";

        //        }
        //        return RedirectToAction("Details", new { id = SellerId });

        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}


        // GET: Product/EditProduct   
        public ActionResult EditSeller(int id)
        {
            SellerRepository ProRepo = new SellerRepository();



            return View(ProRepo.GetAllSellers().Find(Emp => Emp.SellerId == id));

        }

        // POST: Product/EditProduct   
        [HttpPost]

        public ActionResult EditSeller(int id, Seller obj)
        {
            try
            {
                SellerRepository EmpRepo = new SellerRepository();

                EmpRepo.UpdateSeller(obj);
                return RedirectToAction("GetAllSellers");
            }
            catch
            {
                return View();
            }
        }

        // GET: Product/DeleteProduct   
        public ActionResult DeleteSeller(int id)
        {
            try
            {
                SellerRepository ProRepo = new SellerRepository();
                if (ProRepo.DeleteSeller(id))
                {
                    ViewBag.AlertMsg = "Seller details deleted successfully";

                }
                return RedirectToAction("GetAllSellers");

            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Seller/AddSeller.cshtml
@model Market.Models.Seller

@{
    ViewBag.Title = "AddSeller";
}


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">AddSeller</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
        </ul>
    </div>
</nav>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Seller</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MobileNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MobileNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MobileNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-success" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10" style="color:green">
            @ViewBag.Message

        </div>
    </div>
</div>
}
<p></p>

<div>
    @Html.ActionLink("Back to List", "GetAllSellers", null, htmlAttributes: new { @class = "btn btn-primary btn-sm" })
</div>

Views/Seller/AddSellersproduct.cshtml
@model Market.Models.ProductVM

@{
    ViewBag.Title = "AddSellersproduct";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">AddSellerProduct</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
        </ul>
    </div>
</nav>



@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProductVM</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ProductId, (IEnumerable<SelectListItem>)ViewBag.ProList, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "GetAllSellers", null, htmlAttributes: new { @class = "btn btn-primary btn-sm" })
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Views/Seller/Details.cshtml
@model IEnumerable<Market.Models.ViewModel>

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<p>
    @Html.ActionLink("Add New", "AddSellersproduct", "Seller", null, htmlAttributes: new { @class = "btn btn-outline-success" })     |    @Html.ActionLink("Back", "GetAllSellers", "seller", null, htmlAttributes: new { @class = "btn btn-outline-secondary" })
</p>
<table class="table table-striped">
    <tr>
        
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pkgd)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Exp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rating)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pkgd)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Exp)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rating)
        </td>
        <td>
           
            @*@Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
        </td>
    </tr>
}

</table>

Views/Seller/EditSeller.cshtml
@model Market.Models.Seller

@{
    ViewBag.Title = "EditSeller";
}


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">EditSeller</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
        </ul>
    </div>
</nav>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Seller</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SellerId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MobileNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MobileNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MobileNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "GetAllSellers", null, htmlAttributes: new { @class = "btn btn-primary btn-sm" })
</div>

Views/Seller/GetAllSellers.cshtml
@model IEnumerable<Market.Models.Seller>

@{
    ViewBag.Title = "GetAllSellers";
}



<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Sellers</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
        </ul>
    </div>
</nav><p>
    @Html.ActionLink("Create New", "AddSeller", null, htmlAttributes: new { @class = "btn btn-outline-success" })     |    @Html.ActionLink("Home", "Index", "Home", null, htmlAttributes: new { @class = "btn btn-outline-secondary" })
</p>



<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MobileNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th></th>
        </tr>
    </thead>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MobileNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditSeller", new { id = item.SellerId }, htmlAttributes: new { @class = "btn btn-warning" }) |
                @Html.ActionLink("Details", "Details", "Seller", new { id = item.SellerId }, htmlAttributes: new { @class = "btn btn-info" }) |
                @Html.ActionLink("Delete", "DeleteSeller", new { id = item.SellerId }, new { onclick = "return confirm('Confirm Delete?');", @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>

Views/Seller/ViewSell.cshtml
@model Market.Models.Seller

@{
    ViewBag.Title = "ViewSell";
}

<h2>ViewSell</h2>

<div>
    <h4>Seller</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MobileNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MobileNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "EditSeller", new { id = Model.SellerId }) |
    @Html.ActionLink("Back to List", "GetAllSellers", null, htmlAttributes: new { @class = "btn btn-primary btn-sm" })
</p>